# If running in Docker, this should be '0.0.0.0' followed by the mapped port inside the container
address = 'localhost:8080'

[hosts."admin.localhost"]
"" = "https://localhost:5000/"

[hosts."dev.localhost"]
"" = "https://localhost:5050/"
"dashboard" = "https://localhost:5050/dev/dashboard"

[hosts."user.localhost"]
"" = "https://localhost:5000/"
