address = 'localhost:8088'

[hosts."admin.localhost"]
"" = "https://localhost:5000/"

[hosts."dev.localhost"]
"" = "https://localhost:5050/"
"dashboard" = "https://localhost:5050/dev/dashboard"

[hosts."user.localhost"]
"" = "https://localhost:5000/"
